### ISSUE TITLE
Add support for Typescript in Vue

### ISSUE THREAD

**Issue by tuanha168** [marilari88/twoslash-queries.nvim#8]
Hi, can you add support for `script` block in vue when using typescript too.
I'm using `volar` as vue LSP with typescript support.
Thanks

**Comment by marilari88** [comment]
Hi! I'm not aware about vue and vue ecosystem but theoritically this plugin works with other LSP. Can I take a look at your lsp configuration? Can you point me a vue repo in which I can test it?

**Comment by tuanha168** [comment]
Hi, I have my lsp config in this repo
https://github.com/tuanha168/nvim/blob/nvchad/config/lspconfig.lua

You can check this repo to test
https://github.com/epicmaxco/vuestic-admin

Thank you!!!

**Comment by marilari88** [comment]
Hi @tuanha168 , I've just merged #9 . I'd like to have your feedback

**Comment by tuanha168** [comment]
It work!! Thank you so much for supporting!!
